receiver_button = "/avatar/parameters/vrphone_receiver_button"
pickup_button = "/avatar/parameters/vrphone_pickup_button"
hangup_button = "/avatar/parameters/vrphone_hangup_button"
phonebook_entry_1_button = "/avatar/parameters/vrphone_phonebook_entry_1_button"
phonebook_entry_2_button = "/avatar/parameters/vrphone_phonebook_entry_2_button"
phonebook_entry_3_button = "/avatar/parameters/vrphone_phonebook_entry_3_button"
phonebook_entry_4_button = "/avatar/parameters/vrphone_phonebook_entry_4_button"
#Outputs to use as indicators & for logic
call_started = "/avatar/parameters/vrphone_call_started"
call_ended = "/avatar/parameters/vrphone_call_ended"
call_incoming = "/avatar/parameters/vrphone_call_incoming"
call_outgoing = "/avatar/parameters/vrphone_call_outgoing"
call_answered = "/avatar/parameters/vrphone_call_answered"
call_ring = "/avatar/parameters/vrphone_call_ring"
call_busy = "/avatar/parameters/vrphone_call_busy"
